### PR TITLE
30 replace hardcoded data in frontend with graphql queries

### PR DESCRIPTION
**Pull request by ali1373107**

### CODE REVIEW

**Review by AhubSajid — APPROVED** [review]

**Review by tomstrong64 — CHANGES_REQUESTED** [review]
API calls working fine, nice job! But the form seems to be a bit messed up.
@AhubSajid @HamzaMohibe would one of you be able to fix the visual weirdness before merging?
image

**Comment by tomstrong64** [comment]
Just seen this makes calls specifically to localhost:8080 as well, this won't work on the server. Need to proxy the requests through the API server

**Comment by tomstrong64** [comment]
Just pushed changes so that to graphql are proxied through express, it should now work when deployed

**Comment by tomstrong64** [comment]
Tests were failing as the branch was missing changes from main, merged main into this branch

**Review by HamzaMohibe — COMMENTED** [review]
Form alignment is fixed
image

**Review by HamzaMohibe — APPROVED** [review]

**Review by HamzaMohibe — APPROVED** [review]
Form fixed

**Review by HamzaMohibe — APPROVED** [review]

**Review by tomstrong64 — APPROVED** [review]
Nice one!

**Pull request merged**
